/**
 * Capacitor Configuration Generator
 */

import { CapacitorConfigOptions } from '../types/index.js';

/**
 * Generate capacitor.config.ts content
 */
export function generateCapacitorConfig(options: CapacitorConfigOptions): string {
  const { appName, appId, webDir, primaryColor } = options;

  return `import { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: '${appId}',
  appName: '${appName}',
  webDir: '${webDir}',

  server: {
    androidScheme: 'https',
  },

  ios: {
    contentInset: 'automatic',${primaryColor ? `
    backgroundColor: '${primaryColor}',` : ''}
  },

  plugins: {
    SplashScreen: {
      launchShowDuration: 2000,
      backgroundColor: '${primaryColor || '#ffffff'}',
      showSpinner: false,
    },
  },
};

export default config;
`;
}

/**
 * Generate package.json scripts for Capacitor
 */
export function generateCapacitorScripts(framework: string): Record<string, string> {
  const buildCommand = framework === 'nextjs' ? 'next build' :
                       framework === 'vite' ? 'vite build' :
                       'react-scripts build';

  return {
    'cap:sync': 'npx cap sync',
    'cap:open:ios': 'npx cap open ios',
    'cap:run:ios': 'npx cap run ios',
    'build:ios': `${buildCommand} && npx cap sync ios`,
    'open:ios': `${buildCommand} && npx cap sync ios && npx cap open ios`,
  };
}

/**
 * Generate iOS Info.plist permissions template
 */
export function generateInfoPlistPermissions(): string {
  return `<!-- Common iOS Permissions for Capacitor Apps -->
<!-- Add these to ios/App/App/Info.plist as needed -->

<!-- Camera Access -->
<key>NSCameraUsageDescription</key>
<string>This app needs camera access to take photos</string>

<!-- Photo Library -->
<key>NSPhotoLibraryUsageDescription</key>
<string>This app needs photo library access</string>
<key>NSPhotoLibraryAddUsageDescription</key>
<string>This app needs to save photos</string>

<!-- Location (if needed) -->
<key>NSLocationWhenInUseUsageDescription</key>
<string>This app needs location access</string>

<!-- Microphone (if needed) -->
<key>NSMicrophoneUsageDescription</key>
<string>This app needs microphone access</string>

<!-- Contacts (if needed) -->
<key>NSContactsUsageDescription</key>
<string>This app needs contacts access</string>

<!-- Calendar (if needed) -->
<key>NSCalendarsUsageDescription</key>
<string>This app needs calendar access</string>

<!-- Bluetooth (if needed) -->
<key>NSBluetoothAlwaysUsageDescription</key>
<string>This app needs Bluetooth access</string>`;
}

/**
 * Generate .gitignore entries for Capacitor
 */
export function generateGitignoreEntries(): string {
  return `# Capacitor
ios/
android/
*.xcworkspace
*.xcodeproj

# Capacitor Config
capacitor.config.ts.backup`;
}

/**
 * Generate complete setup guide
 */
export function generateSetupGuide(options: CapacitorConfigOptions): string {
  const { appName, appId, webDir, framework } = options;

  return `# ${appName} - iOS Setup Guide

## Prerequisites

- Xcode 14.0+ installed
- CocoaPods installed (\`brew install cocoapods\`)
- Node.js 18+ installed

## Step 1: Install Capacitor

\`\`\`bash
npm install @capacitor/core @capacitor/cli
npm install @capacitor/ios
\`\`\`

## Step 2: Initialize Capacitor

\`\`\`bash
npx cap init "${appName}" "${appId}" --web-dir="${webDir}"
\`\`\`

## Step 3: Build Your Web App

\`\`\`bash
npm run build
\`\`\`

${framework === 'nextjs' ? `
### Next.js Specific

Ensure \`next.config.js\` has:

\`\`\`javascript
module.exports = {
  output: 'export',
  images: {
    unoptimized: true,
  },
};
\`\`\`
` : ''}

${framework === 'vite' ? `
### Vite Specific

Ensure \`vite.config.ts\` has:

\`\`\`typescript
export default defineConfig({
  base: './',
  build: {
    outDir: '${webDir}',
  },
});
\`\`\`
` : ''}

## Step 4: Add iOS Platform

\`\`\`bash
npx cap add ios
\`\`\`

## Step 5: Sync Web Code

\`\`\`bash
npx cap sync ios
\`\`\`

## Step 6: Open in Xcode

\`\`\`bash
npx cap open ios
\`\`\`

## Step 7: Configure Xcode

1. Select your development team in "Signing & Capabilities"
2. Set deployment target to iOS 13.0+
3. Add app icon (1024x1024)
4. Configure splash screen

## Step 8: Build & Run

Press ⌘R in Xcode to build and run on simulator or device.

## Useful Commands

\`\`\`bash
# Rebuild and sync
npm run build:ios

# Open Xcode
npm run open:ios

# Run on device
npm run cap:run:ios
\`\`\`

## Troubleshooting

### Build Errors

- Clean build folder: Product → Clean Build Folder (⇧⌘K)
- Reset CocoaPods: \`cd ios/App && pod deintegrate && pod install\`

### White Screen

- Check browser console in Safari Web Inspector
- Verify base path is './' in config
- Ensure all assets use relative paths

### API Calls Failing

- Use absolute URLs for API endpoints
- Check CORS configuration on backend
- Verify network permissions in Info.plist

---

Generated by web-to-ios-mcp`;
}
